nome = str(input('Digite seu nome completo:'))
print(nome.upper())
print(nome.lower())
print('Seu nome completo tem {} letras.'.format(len(nome.replace(' ',''))))
nomeSplitado = nome.split()
print('Seu primeiro nome tem {} letras.'.format(len(nomeSplitado[0])))
